// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQTAnmz5Srmn2D7GfKLRbY6qmFx0ZFaJE',
    appId: '1:862348085059:web:b8b1309e3b5b4f2c2351f6',
    messagingSenderId: '862348085059',
    projectId: 'worldofbooksalim',
    authDomain: 'worldofbooksalim.firebaseapp.com',
    storageBucket: 'worldofbooksalim.firebasestorage.app',
    measurementId: 'G-YD3X5MPQY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe5yCXCPM-gO5MQ_RnVWlbfeoF4abENkY',
    appId: '1:862348085059:android:56a1039bc874dee52351f6',
    messagingSenderId: '862348085059',
    projectId: 'worldofbooksalim',
    storageBucket: 'worldofbooksalim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW_qSgM1l5Ar3AcErGxFOilJplAcpRiyA',
    appId: '1:862348085059:ios:915b6143e33059de2351f6',
    messagingSenderId: '862348085059',
    projectId: 'worldofbooksalim',
    storageBucket: 'worldofbooksalim.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW_qSgM1l5Ar3AcErGxFOilJplAcpRiyA',
    appId: '1:862348085059:ios:915b6143e33059de2351f6',
    messagingSenderId: '862348085059',
    projectId: 'worldofbooksalim',
    storageBucket: 'worldofbooksalim.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQTAnmz5Srmn2D7GfKLRbY6qmFx0ZFaJE',
    appId: '1:862348085059:web:51469ce2f34c4d152351f6',
    messagingSenderId: '862348085059',
    projectId: 'worldofbooksalim',
    authDomain: 'worldofbooksalim.firebaseapp.com',
    storageBucket: 'worldofbooksalim.firebasestorage.app',
    measurementId: 'G-LPK5EZSX9N',
  );
}
